server:
  port: 8090
spring:
  application:
    name: myzuulclient

management:
  security:
    enabled: false #为了端点的测试需要关闭安全认证

#zuul的全套配置begin-----------------------
zuul:
  routes:
    sourcezjm:   #  sourcezjm(可修改)的url请求都会转发至http://localhost:8081
      url: http://localhost:8081  #简单路由，可以省略path配置,没有path的话sourcezjm当后缀直接访问
    zuultest:
      path: /zuultest/**     # 所有zuultest开头的请求路径都会转发至:springboot-serviceprovider3的服务id
      serviceId: serviceprovider   #服务提供者，ribbon路由
    forwardZuul:
          path: /forwardZuul/**
          url: forward:/forwardZuul_test1 #转发路由 URL参数需要由forward:...构成 访问方式->http://localhost:8090/forwardZuul/**

# http://localhost:8090/routes 可进行端点访问查看映射列表
#zuul的全套配置end-----------------------

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/